const language = {
  en: {
    search: "Search",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcomingMovie: "Upcoming Movie",
    Netfix: "NETFIX",
    "Search Your Movie Here 🔎": "Search Your Movie Here 🔎",
    "Enter your Name": "Enter your Name",
    "Email Address": "Email Address",
    Password: "Password",
    "Already have an account": "Already have an account",
    "New to Netflix ?": "New to Netflix ?",
    Submit: "Submit",
    "Loading...": "Loading...",
    "▶️ Play": "▶️ Play",
    "ℹ️ More info": "ℹ️ More info",
    "What would you like to watch": "What would you like to watch",
  },
  hindi: {
    search: "खोजें",
    signIn: "साइन इन करें",
    signUp: "साइन अप करें",
    signOut: "साइन आउट करें",
    nowPlaying: "अब चल रही है",
    popular: "लोकप्रिय",
    topRated: "शीर्ष रेटेड",
    upcomingMovie: "आगामी मूवी",
    Netfix: "नेटफिक्स",
    "Search Your Movie Here 🔎": "अपनी मूवी यहाँ खोजें 🔎",
    "Enter your Name": "अपना नाम दर्ज करें",
    "Email Address": "ईमेल पता",
    Password: "पासवर्ड",
    "Already have an account": "पहले से ही एक खाता है",
    "New to Netflix ?": "Netflix में नया हैं ?",
    Submit: "प्रस्तुत",
    "Loading...": "लोड हो रहा है...",
    "▶️ Play": "▶️ प्ले",
    "ℹ️ More info": "ℹ️ अधिक जानकारी",
    "What would you like to watch": "आप क्या देखना चाहेंगे",
  },
  spanish: {
    search: "Buscar",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    signOut: "Cerrar sesión",
    nowPlaying: "En cartelera",
    popular: "Popular",
    topRated: "Mejor valoradas",
    upcomingMovie: "Próximamente",
    Netfix: "NETFIX",
    "Search Your Movie Here 🔎": "Buscar tu película aquí 🔎",
    "Enter your Name": "Ingrese su nombre",
    "Email Address": "Dirección de correo electrónico",
    Password: "Contraseña",
    "Already have an account": "¿Ya tienes una cuenta?",
    "New to Netflix ?": "¿Nuevo en Netflix?",
    Submit: "Enviar",
    "Loading...": "Cargando...",
    "▶️ Play": "▶️ Reproducir",
    "ℹ️ More info": "ℹ️ Más información",
    "What would you like to watch": "¿Qué te gustaría ver?",
  },
  japanese: {
    search: "検索",
    signIn: "サインイン",
    signUp: "サインアップ",
    signOut: "サインアウト",
    nowPlaying: "上映中",
    popular: "人気",
    topRated: "トップ評価",
    upcomingMovie: "公開予定",
    Netfix: "ネットフリックス",
    "Search Your Movie Here 🔎": "映画を検索 🔎",
    "Enter your Name": "お名前を入力してください",
    "Email Address": "メールアドレス",
    Password: "パスワード",
    "Already have an account": "既にアカウントをお持ちですか？",
    "New to Netflix ?": "Netflixを初めてご利用ですか？",
    Submit: "送信",
    "Loading...": "読み込み中...",
    "▶️ Play": "▶️ 再生",
    "ℹ️ More info": "ℹ️ 詳細",
    "What would you like to watch": "何をご覧になりたいですか？",
  },
  french: {
    search: "Rechercher",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    signOut: "Se déconnecter",
    nowPlaying: "À l'affiche",
    popular: "Populaire",
    topRated: "Les mieux notés",
    upcomingMovie: "Prochainement",
    Netfix: "NETFIX",
    "Search Your Movie Here 🔎": "Rechercher votre film ici 🔎",
    "Enter your Name": "Entrez votre nom",
    "Email Address": "Adresse e-mail",
    Password: "Mot de passe",
    "Already have an account": "Vous avez déjà un compte ?",
    "New to Netflix ?": "Nouveau sur Netflix ?",
    Submit: "Soumettre",
    "Loading...": "Chargement...",
    "▶️ Play": "▶️ Lire",
    "ℹ️ More info": "ℹ️ Plus d'infos",
    "What would you like to watch": "Qu'est-ce que vous aimeriez regarder ?",
  },
};

export default language;
